parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  sourceType: 'module'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
root: true
env:
  node: true
ignorePatterns:
  - '.eslintrc.yaml'
rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
overrides:
  - files:
      - '**/*.test.ts'
      - '**/*.spec.ts'
      - '**/*.test.js'
      - '**/*.spec.js'
    env:
      jest: true
    extends:
      - 'plugin:jest/recommended'
    plugins:
      - 'jest'
    rules:
      '@typescript-eslint/interface-name-prefix': 'off'
      '@typescript-eslint/explicit-function-return-type': 'off'
      '@typescript-eslint/explicit-module-boundary-types': 'off'
      '@typescript-eslint/no-explicit-any': 'off'
      '@typescript-eslint/no-empty-interface': 'off'
      '@typescript-eslint/no-unused-vars': 'off'
      'jest/expect-expect': 'off'


