name: Coverage

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
