name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      run: chmod +x ./docker-deploy.sh && ./docker-deploy.sh
